### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './cad_sim/stl_repo'

### ISSUE THREAD

**Issue by chenfeng15a** [vardhah/Constraint_BO_UUV_hull_design#2]
Dear Vardhah:
         Actually, once everything is installed, if I didn't make a directory ./cad_sim/stl_repo and copy  ./cfd_sim/stl_cfd/swordfish1.stl to ./cad_sim/stl_repo, when I run 'main_bo.py' , error occurs:

> *** ALL DONE -- ALL DONE ***
*Copied directory from ./cad_sim/stl_repo to destination: ./cfd_sim/stl_cfd
Traceback (most recent call last):
  File "main_bo.py", line 161, in <module>
    run_bo(run[i],aqu2,seeds[i])
  File "main_bo.py", line 143, in run_bo
    myBopt2D.run_optimization(batch,verbosity=True)
  File "/home/cf/GPyOpt/GPyOpt/core/bo.py", line 156, in run_optimization
    self.evaluate_objective()
  File "/home/cf/GPyOpt/GPyOpt/core/bo.py", line 202, in evaluate_objective
    self.Y_new, cost_new = self.objective.evaluate(self.suggested_sample)
  File "/home/cf/GPyOpt/GPyOpt/core/task/objective.py", line 50, in evaluate
    f_evals, cost_evals = self._eval_func(x)
  File "/home/cf/GPyOpt/GPyOpt/core/task/objective.py", line 74, in _eval_func
    rlt = self.func(np.atleast_2d(x[i]))
  File "main_bo.py", line 80, in run_cad_cfd
    copy_dir(src,dst)
  File "main_bo.py", line 53, in copy_dir
    shutil.copytree(src, dst)
  File "/home/cf/anaconda3/envs/opt37/lib/python3.7/shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: './cad_sim/stl_repo'

**Comment by vardhah** [comment]
just create an empty folder name 'stl_repo' in the cad_sim folder. It should do the job. Let me know if it doesnot
